### ISSUE TITLE
Call to undefined method getResourceTypes

### ISSUE THREAD

**Issue by murathalici** [contentacms/contenta_jsonapi#262]
I am getting the following error after updating to the latest version of [JSON API](https://www.drupal.org/project/jsonapi_extras) and [JSON API Extras](https://www.drupal.org/project/jsonapi_extras)

`The website encountered an unexpected error. Please try again later.
Error: Call to undefined method Drupal\jsonapi\ResourceType\ResourceTypeRepository::getResourceTypes() in Drupal\contenta_enhancements\Controller\OpenApiDocs->generateDocs() (line 68 of profiles/contrib/contenta_jsonapi/modules/contenta_enhancements/src/Controller/OpenApiDocs.php).
`

**Comment by e0ipso** [comment]
Thanks for the report!

**Comment by ftaiolivista** [comment]
Clean install by composer

I think is related
```
The website encountered an unexpected error. Please try again later.</br></br><em class="placeholder">Symfony\Component\Routing\Exception\ResourceNotFoundException</em>: No routes found for &quot;/node/81&quot;. in <em class="placeholder">Drupal\Core\Routing\Router-&gt;matchRequest()</em> (line <em class="placeholder">159</em> of <em class="placeholder">core/lib/Drupal/Core/Routing/Router.php</em>). <pre class="backtrace">Drupal\jsonapi\LinkManager\LinkManager-&gt;getRequestLink(Object) (Line: 141)
Drupal\jsonapi\Normalizer\Value\JsonApiDocumentTopLevelNormalizerValue-&gt;rasterizeValue() (Line: 203)
Drupal\jsonapi\Normalizer\JsonApiDocumentTopLevelNormalizer-&gt;normalize(Object, &#039;api_json&#039;, Array) (Line: 142)
Symfony\Component\Serializer\Serializer-&gt;normalize(Object, &#039;api_json&#039;, Array) (Line: 46)
Drupal\jsonapi\Serializer\Serializer-&gt;normalize(Object, &#039;api_json&#039;, Array) (Line: 86)
Drupal\jsonapi\EntityToJsonApi-&gt;normalize(Object) (Line: 369)
contenta_enhancements_node_view_alter(Array, Object, Object) (Line: 501)
Drupal\Core\Extension\ModuleHandler-&gt;alter(&#039;node_view&#039;, Array, Object, Object) (Line: 285)
Drupal\Core\Entity\EntityViewBuilder-&gt;buildMultiple(Array) (Line: 220)
Drupal\Core\Entity\EntityViewBuilder-&gt;build(Array)
call_user_func(Array, Array) (Line: 378)
Drupal\Core\Render\Renderer-&gt;doRender(Array, ) (Line: 195)
Drupal\Core\Render\Renderer-&gt;render(Array, ) (Line: 226)
Drupal\Core\Render\MainContent\HtmlRenderer-&gt;Drupal\Core\Render\MainContent\{closure}() (Line: 582)
Drupal\Core\Render\Renderer-&gt;executeInRenderContext(Object, Object) (Line: 227)
Drupal\Core\Render\MainContent\HtmlRenderer-&gt;prepare(Array, Object, Object) (Line: 117)
Drupal\Core\Render\MainContent\HtmlRenderer-&gt;renderResponse(Array, Object, Object) (Line: 90)
Drupal\Core\EventSubscriber\MainContentViewSubscriber-&gt;onViewRenderArray(Object, &#039;kernel.view&#039;, Object) (Line: 108)
Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher-&gt;dispatch(&#039;kernel.view&#039;, Object) (Line: 158)
Symfony\Component\HttpKernel\HttpKernel-&gt;handleRaw(Object, 1) (Line: 68)
Symfony\Component\HttpKernel\HttpKernel-&gt;handle(Object, 1, 1) (Line: 67)
Drupal\simple_oauth\HttpMiddleware\BasicAuthSwap-&gt;handle(Object, 1, 1) (Line: 57)
Drupal\Core\StackMiddleware\Session-&gt;handle(Object, 1, 1) (Line: 47)
Drupal\Core\StackMiddleware\KernelPreHandle-&gt;handle(Object, 1, 1) (Line: 99)
Drupal\page_cache\StackMiddleware\PageCache-&gt;pass(Object, 1, 1) (Line: 78)
Drupal\page_cache\StackMiddleware\PageCache-&gt;handle(Object, 1, 1) (Line: 40)
Drupal\jsonapi\StackMiddleware\FormatSetter-&gt;handle(Object, 1, 1) (Line: 48)
Asm89\Stack\Cors-&gt;handle(Object, 1, 1) (Line: 47)
Drupal\Core\StackMiddleware\ReverseProxyMiddleware-&gt;handle(Object, 1, 1) (Line: 50)
Drupal\Core\StackMiddleware\NegotiationMiddleware-&gt;handle(Object, 1, 1) (Line: 23)
Stack\StackedHttpKernel-&gt;handle(Object, 1, 1) (Line: 657)
Drupal\Core\DrupalKernel-&gt;handle(Object) (Line: 19)
require(&#039;/home/vista/www/contenta/web/index.php&#039;) (Line: 96)
</pre>
```

**Comment by e0ipso** [comment]
Thanks for the report. This is blocked on https://www.drupal.org/project/jsonapi/issues/2949632.

**Comment by e0ipso** [comment]
This was resolved in the issue linked above.

Please update with: `composer update --with-dependencies drupal/jsonapi_extras drupal/jsonapi` to resolve this.

Thanks!

**Comment by novia713** [comment]
i did the suggested `composer update` but the problem remains for me
i get the following error
```
Error: Call to undefined method Drupal\jsonapi_extras\ResourceType\ConfigurableResourceTypeRepository::getResourceTypes() in Drupal\contenta_enhancements\Controller\OpenApiDocs->generateDocs() (line 68 of profiles/contrib/contenta_jsonapi/modules/contenta_enhancements/src/Controller/OpenApiDocs.php).
```

mine is an old project, these are my required projects:
```
"contentacms/contenta_jsonapi": "dev-8.x-1.x#67f9552",
        "composer/installers": "^1.2",
        "drupal-composer/drupal-scaffold": "^2.2",
        "cweagans/composer-patches": "~1.0",
        "drupal/core": "8.4.x-dev#3758b3e",
        "drush/drush": "~8.0",
        "drupal/console": "~1.0",
        "drupal/coffee": "^1.0@beta",
        "drupal/devel": "^1.2",
        "drupal/jsonapi_file": "^1.1",
        "drupal/whoops": "^1.0@beta",
        "drupal/content_access": "^1.0@alpha",
        "drupal/field_permissions": "^1.0",
        "drupal/config_inspector": "^1.0"

```

**Comment by thegurf** [comment]
I tried the suggested update fix as well and am getting the same error described above.

**Comment by popstas** [comment]
Tried `composer update` and `composer update --with-dependencies drupal/jsonapi_extras drupal/jsonapi`, still error present.

drupal/jsonapi                    1.12.0
drupal/jsonapi_extras             1.0.0-rc7

**Comment by e0ipso** [comment]
I apologize for the confusion. I had to merge https://github.com/contentacms/contenta_jsonapi/pull/263 before. Now it should all be well.

**Comment by novia713** [comment]
tried a `composer up -o --prefer-dist` and this bug was gone. thanks

**Comment by popstas** [comment]
@e0ipso, after git pull all works, thank you!

**Comment by shrop** [comment]
@novia713 's suggested `composer up -o --prefer-dist` worked for me also

**Comment by cmoeser** [comment]
When running  composer up -o --prefer-dist I get the following error:

  - Installing asm89/stack-cors (1.1.0): Loading from cache
  - Applying patches for asm89/stack-cors
    patches/asm89_stack-cors/pull_request_42.patch ((November 29 2017 06:22:06 PM: See issue #223 on contentacms/contenta_jsonapi) Add origin matcher for wildcard matching)
   Could not apply patch! Skipping. The error was: Cannot apply patch patches/asm89_stack-cors/pull_request_42.patch

  - Installing drupal/core (8.4.5): Loading from cache
  - Applying patches for drupal/core
    https://www.drupal.org/files/issues/drupal-n2788777-105.patch (Allow a profile to be installed from existing config)
   Could not apply patch! Skipping. The error was: Cannot apply patch https://www.drupal.org/files/issues/drupal-n2788777-105.patch

  - Installing drupal/jsonapi (1.14.0): Loading from cache
  - Applying patches for drupal/jsonapi
    https://www.drupal.org/files/issues/2929600--use-full-url-file--2.patch (Make the file URLs full URLs)
   Could not apply patch! Skipping. The error was: Cannot apply patch https://www.drupal.org/files/issues/2929600--use-full-url-file--2.patch
