### ISSUE TITLE
Disable resources

### ISSUE THREAD

**Issue by e0ipso** [contentacms/contenta_jsonapi#63]
Some resources are exposed by default and we want to disable them using JSON API Extras.

  - `node--tutorial`
  - `search_page--search_page`

**Comment by wimleers** [comment]
Note you'll also have to explicitly do it for `openapi`, until https://www.drupal.org/node/2887868 is fixed.

**Comment by recidive** [comment]
Hello @wimleers we found also that fields disabled in jsonapi_extras are still showing up in openapi docs. Is there an issue for this yet? I'm not sure where to look to try to fix this.

Thanks!

**Comment by e0ipso** [comment]
@recidive @wimleers that issue has been addressed. Please update your thingies. :-)

**Comment by e0ipso** [comment]
As said above. This was fixed.
